global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'order_app'
    static_configs:
      - targets: ['order_app:8006']
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
