apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: app
  JWT_ALG: "HS256"
  JWT_EXP: "21000"
  JWT_SECRET: "SECRET"
  DATABASE_URL: "postgresql://app:app@order_app_db:5432/app"
  DATABASE_URL_PAYMENT: "postgresql://app:app@payment_app_db:5432/payment_app_db"
  DATABASE_URL_INVENTORY: "postgresql://app:app@inventory_app_db:5432/inventory_app_db"
  DATABASE_URL_DELIVERY: "postgresql://app:app@delivery_app_db:5432/delivery_app_db"
  REDIS_URL: "redis://:myStrongPassword@redis:6379"
  SITE_DOMAIN: "127.0.0.1"
  SECURE_COOKIES: "false"
  CELERY_BROKER_URL: "redis://:myStrongPassword@redis:6379"
  CELERY_RESULT_BACKEND: "redis://:myStrongPassword@redis:6379"
  ENVIRONMENT: "LOCAL"
  CORS_HEADERS: '["*"]'
  CORS_ORIGINS: '["http://localhost:3000"]'
