apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ghcr.io/scalable-p4/order_service/p4-app:latest
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: regcred