apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-worker
  template:
    metadata:
      labels:
        app: delivery-worker
    spec:
      containers:
      - name: delivery-worker
        image: ghcr.io/scalable-p4/order_service/p4-app:latest
        command: ["celery", "-A", "src.make_delivery", "worker", "--loglevel=info", "--queues", "q04"]
        envFrom:
        - configMapRef:
            name: app-config
        volumeMounts:
        - name: delivery-app-volume
          mountPath: /order_app
      volumes:
      - name: delivery-app-volume
        persistentVolumeClaim:
          claimName: delivery-app-pvc
