apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app-deployment
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-app-container
          image: ghcr.io/scalable-p4/inventory_service/p4-inventory-app:latest
          command: ["./scripts/start-dev.sh"]
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8002
      volumes:
        - name: inventory-app-volume
          persistentVolumeClaim:
            claimName: inventory-app-pvc
      imagePullSecrets:
        - name: regcred
