apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-worker
  template:
    metadata:
      labels:
        app: inventory-worker
    spec:
      containers:
      - name: inventory-worker
        image: ghcr.io/scalable-p4/inventory_service/p4-inventory-app:latest
        command: ["celery", "-A", "src.update_inventory", "worker", "--loglevel=info", "--queues", "q03"]
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: inventory-app-volume
        persistentVolumeClaim:
          claimName: inventory-app-pvc
      imagePullSecrets:
        - name: regcred
