apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
  labels:
    app: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
        - name: order-app-container
          image: ghcr.io/scalable-p4/order_service/p4-order-app:latest
          command: ["./scripts/start-dev.sh"]
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8000
      volumes:
        - name: order-app-volume
          persistentVolumeClaim:
            claimName: order-app-pvc
      imagePullSecrets:
        - name: regcred
