apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      containers:
      - name: order-worker
        image: ghcr.io/scalable-p4/order_service/p4-order-app:latest
        command: ["celery", "-A", "src.create_order", "worker", "--loglevel=info", "--queues", "q01"]
        envFrom:
        - configMapRef:
            name: app-config
      volumes:
      - name: order-app-volume
        persistentVolumeClaim:
          claimName: order-app-pvc
      imagePullSecrets:
        - name: regcred
